=== Brandbank/Coverage/Schemas/coverage.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
	"version": "3.1.0",
	"title": "Coverage Item set",
    "type": "array",
    "items": {
        "title": "Coverage Item",
		"type": "object",
		"properties": {
			"ownLabel": {
				"description": "Is Product Own Label",
				"type": "boolean"
			},
			"hasImage": {
				"description": "Has an image",
				"type": "boolean"
			},
			"description": {
				"description": "Product description",
				"type": "string",
				"minLength": 1
			},
			"rangedOnlineDate": {
				"description": "Date Product is (or will be) displayed online (UTC)",
				"type": "string",
				"format": "date-time"
			},
			"retailerId": {
				"description": "Retailers Product Id",
				"type": "string",
				"minLength": 1
			},
			"gtins": {
				"title": "GTIN set",
				"type": "array",
				"items": {
					"title": "GTIN",
					"type": "object",
					"properties": {
						"gtin": {
							"description": "GTIN / EAN",
							"type": "string",
							"maxLength": 14
						},
						"supplier": {
							"description": "Supplier for the GTIN / EAN",
							"type": "string",
							"minLength": 1
						},
						"preferred": {
							"description": "Preferred supplier",
							"type": "boolean"
						}
					},
					"required": [
						"gtin", "supplier"
					]
				},
				"minItems": 1,
				"uniqueItems": true
			},
			"categories": {
				"title": "Category set",
				"type": "array",
				"items": {
					"title": "Category",
					"type": "object",
					"properties": {
						"level": {
							"description": "Category level",
							"type": "integer",
							"minimum": 1,
							"maximum": 4
						},
						"code": {
							"description": "Category group code",
							"type": "string",
							"minLength": 1
						},
						"value": {
							"description": "Category group",
							"type": "string",
							"minLength": 1
						}
					},
					"required": [
						"level", "code", "value"
					]
				},
				"minItems": 0,
				"uniqueItems": true
			},
			"extensions": {
				"title": "Extension set",
				"type": "array",
				"items": {
					"title": "Extension",
					"type": "object",
					"properties": {
						"code": {
							"description": "Extension Type",
							"type": "string"
						},
						"value": {
							"description": "Extension Value",
							"type": "string"
						}
					},
					"required": [
						"code", "value"
					]
				},
				"minItems": 0,
				"uniqueItems": true
			}
		},
		"required": [
			"ownLabel", "description", "retailerId", "gtins"
		]
    },
    "minItems": 1
}

=== Brandbank/Coverage/Examples/example.json
[
    {
        "ownLabel": false,
        "description": "Delicious Test Beverage #1",
        "retailerId": "55001",
        "rangedOnlineDate": "2018-09-17T00:00:00.000+01:00",
        "gtins": [
            {
                "gtin": "005",
                "supplier": "Jasons Testy Beverages"
            },
            {
                "gtin": "0055000000001",
                "supplier": "Jasons Competitor's Testy Beverages",
              	"preferred": true
            }
        ],
        "categories": [
            {
                "level": 1,
              	"code": "1",
                "value": "Category1"
            },
            {
              	"level": 2,
                "code": "1.1",
                "value": "Category1.1"
            },
            {
              	"level": 3,
                "code": "1.1.1",
                "value": "Category1.1.1"
            },
            {
              	"level": 4,
                "code": "1.1.1.1",
                "value": "Category1.1.1.1"
            }
        ],
      	"extensions": [
      		{
      			"code": "Promotional",
      			"value": "Buy one get one free"
    		}
      	]
    },
    {
        "ownLabel": false,
        "description": "Delicious Test Beverage #2",
        "retailerId": "55002",
        "rangedOnlineDate": "2018-04-01T00:00:00.000",
        "gtins": [
            {
                "gtin": "0055000000004",
                "supplier": "Jasons Testy Beverages",
                "preferred": true
            },
            {
                "gtin": "0055000000003",
                "supplier": "Jasons Competitor's Testy Beverages"
            }
        ],
        "categories": [
            {
                "level": 1,
                "code": "2",
                "value": "Ambient"
            }
        ],
      	"extensions": [
      		{
      			"code": "Promotional",
      			"value": "50% extra free"
    		}
      	]
    }
]
